[project]
name = "carvalueml-ai-driven-car-price-estimation"
version = "0.1.0"
description = "This package contains production level implementation of carvalue ml application."
authors = [
    {name = "amulyaprasanth",email = "amulyaprasanth301@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "hopsworks (>=4.1.8,<5.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "gradio (>=5.19.0,<6.0.0)",
    "xgboost (>=2.1.4,<3.0.0)",
    "catboost (>=1.2.7,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "pytest (>=8.3.4,<9.0.0)",
    "beautifulsoup4 (>=4.13.3,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
python-dotenv = "^1.0.1"

